# Created using wingetcreate 1.1.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.2.0.schema.json

PackageIdentifier: DonHOdon.h@free.fr.Notepad++
PackageVersion: 8.4.6.0
Installers:
- Architecture: x64
  InstallerType: nullsoft
  InstallerUrl: https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.4.6/npp.8.4.6.Installer.x64.exe
  InstallerSha256: 7E33C60A78C48D0F899D9D8C3980DEECF5C7AE8BBFF742C77D5BC35794728594
ManifestType: installer
ManifestVersion: 1.2.0

